"use client"

import { useRole } from "@/lib/context/role-context"
import { redirect } from "next/navigation"
import { useEffect } from "react"
import HelpToggle from "@/components/overlays/help-toggle"
import ReportSummaryCards from "@/components/admin/exports/ReportSummaryCards"
import AgentReportTable from "@/components/admin/exports/AgentReportTable"
import MockExportPanel from "@/components/admin/exports/MockExportPanel"

const ReportingCenterPage = () => {
  const { currentRole } = useRole()
  const normalizedRole = currentRole.toLowerCase()

  // RBAC: Only admin and CEO can access Reporting Center
  const isCEO = normalizedRole === "ceo"
  const isAdmin = normalizedRole === "admin"
  const hasAccess = isCEO || isAdmin

  useEffect(() => {
    console.log("Loaded: ReportingCenterPage")

    if (!hasAccess) {
      redirect("/unauthorized")
    }
  }, [hasAccess])

  // Read-only mode for admin users
  const isReadOnlyMode = isAdmin && !isCEO
  const canExecuteActions = isCEO

  if (!hasAccess) {
    return null // Prevent flash before redirect
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-[#0b1323] to-[#101d34] text-white px-6 py-10 max-w-screen-xl mx-auto">
      <div className="space-y-6">
        {/* Header Section */}
        <div className="bg-[#0f1a2c]/80 border border-cyan-500/20 backdrop-blur-sm rounded-xl p-6 shadow-cyan-500/10 shadow-sm">
          <div className="flex justify-between items-center mb-6">
            <div>
              <h1 className="text-3xl font-bold text-cyan-400">Reporting Center</h1>
              <p className="text-blue-300">Centralized agent-driven reporting and data exports.</p>
            </div>
            <HelpToggle
              title="Reporting Center Help"
              content={
                <ul className="list-disc ml-4">
                  <li>View comprehensive reports generated by AI agents</li>
                  <li>Export data in multiple formats (CSV, PDF, JSON)</li>
                  <li>Track report generation status and agent ownership</li>
                  <li>Monitor compliance and audit trail for all exports</li>
                  <li>Access historical reporting data and trends</li>
                </ul>
              }
            />
          </div>

          {/* Read-Only Banner for Admin Users */}
          {isReadOnlyMode && (
            <div className="bg-yellow-500/10 border border-yellow-500/20 text-yellow-300 text-sm px-4 py-3 rounded-lg mb-6 flex items-center gap-2">
              <div className="w-2 h-2 bg-yellow-400 rounded-full"></div>
              <span>
                You are viewing the Reporting Center in read-only mode. Only the CEO may execute report generation
                actions.
              </span>
            </div>
          )}
        </div>

        {/* Report Summary Cards */}
        <ReportSummaryCards />

        {/* Agent Report Table */}
        <AgentReportTable canExecuteActions={canExecuteActions} isReadOnlyMode={isReadOnlyMode} />

        {/* Mock Export Panel */}
        <MockExportPanel canExecuteActions={canExecuteActions} isReadOnlyMode={isReadOnlyMode} />
      </div>
    </div>
  )
}

export default ReportingCenterPage
